"""hqbacktest - A-share quantitative strategy backtest and trading simulation engine."""

from hqbacktest.data import (
    CacheKey,
    DataCache,
    DataVersion,
    DataView,
    HqDataCsvPortal,
    InMemoryDataPortal,
    MarketDataPortal,
    resolve_source_location,
)
from hqbacktest.domain import (
    AccountSnapshot,
    AdjustmentPolicy,
    Bar,
    CorporateActionAdjustment,
    EventType,
    Fill,
    Order,
    OrderStatus,
    OrderType,
    Portfolio,
    Position,
    PositionSnapshot,
    PriceMode,
    RejectReason,
    Side,
)
from hqbacktest.engine import (
    BacktestConfig,
    BacktestEngine,
    BacktestResult,
    BaseStrategy,
    Context,
    CorporateAction,
    CorporateActionProvider,
    CostModel,
    DefaultCostModel,
    EngineEvent,
    EventLog,
    FactorDiagnostic,
    FactorDiagnosticCollector,
    NullStrategy,
    SimulatedBroker,
    Strategy,
    TradingDayIterator,
    TradingRuleSet,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "AccountSnapshot",
    "AdjustmentPolicy",
    "BacktestConfig",
    "BacktestEngine",
    "BacktestResult",
    "Bar",
    "BaseStrategy",
    "CacheKey",
    "Context",
    "CorporateAction",
    "CorporateActionAdjustment",
    "CorporateActionProvider",
    "CostModel",
    "DataCache",
    "DataVersion",
    "DataView",
    "DefaultCostModel",
    "EngineEvent",
    "EventLog",
    "EventType",
    "FactorDiagnostic",
    "FactorDiagnosticCollector",
    "Fill",
    "HqDataCsvPortal",
    "InMemoryDataPortal",
    "MarketDataPortal",
    "NullStrategy",
    "Order",
    "OrderStatus",
    "OrderType",
    "Portfolio",
    "Position",
    "PositionSnapshot",
    "PriceMode",
    "RejectReason",
    "Side",
    "SimulatedBroker",
    "Strategy",
    "TradingDayIterator",
    "TradingRuleSet",
    "resolve_source_location",
]
